name: GitHub Stats

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate GitHub Readme Stats
        uses: anuraghazra/github-readme-stats@v2
        with:
          username: ThiagoTEP
          token: ${{ secrets.MY_GITHUB_TOKEN }}
