name: Generate GitHub Stats

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # Certifique-se de usar o nome correto do secret
      - name: Generate GitHub Readme Stats
        uses: anuraghazra/github-readme-stats@v1  # Usando a versão estável v1
        with:
          username: ThiagoTEP  # Seu nome de usuário GitHub
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # Usando o token correto
